"""Set up all data splits under data/ with short, consistent names.

Input   (generated by third_part_code/medLLMbenchmark/MIMIC-IV-Ext-Creation.py):
  MIMIC-IV-Ext-Triage-Specialty-Diagnosis-Decision-Support.csv  ->  data/test.csv
  MIMIC-IV-Ext-Dev.csv                                          ->  (source pool, not saved)

Outputs (all gitignored, regenerate with this script):
  data/splits/test.csv     -  2 200 rows  -- NEVER TOUCH until final paper results
  data/splits/val.csv      -  2 000 rows  -- locked eval set for comparing RAG versions
  data/splits/scratch.csv  -    100 rows  -- immediate scaffolding runs
  data/splits/dev.csv      - 18 949 rows  -- free development pool (source minus val)
  data/splits/dev_tune.csv -  1 000 rows  -- experiment strategy selection (E00.5–E04)
  data/splits/dev_holdout.csv -  500 rows  -- final holdout confirmation (E05, run once)

Split strategy
--------------
- Plain random sample (no stratification). Triage-level proportions were
  verified to be stable across the pool (<= 1.7 pp deviation), so forced
  stratification adds no statistical benefit. ESI 4 is too rare (<0.5%) to
  meaningfully balance via stratification in any case.
- Seed 42 is fixed throughout so splits are exactly reproducible.
- Val is sampled first; scratch is drawn from dev (source minus val), so
  test / val / scratch are all disjoint.
- dev.csv is the remainder after val is removed: the rows you actually
  iterate on for prompt development, ablations, and potential RL training.
  scratch is a 100-row subset of dev for quick pipeline checks.

Test set firewall
-----------------
data/splits/test.csv is OFF-LIMITS until final paper evaluation. This script
copies it to data/splits/ for naming consistency only -- do not load it during
development.
"""

import argparse
import os
import shutil
import sys

import numpy as np
import pandas as pd


_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_HERE)
_UPSTREAM = os.path.join(_REPO_ROOT, "third_part_code", "medLLMbenchmark")
_SPLITS_DIR = os.path.join(_REPO_ROOT, "data", "splits")

# Upstream source paths (outputs of MIMIC-IV-Ext-Creation.py)
_SRC_TEST = os.path.join(_UPSTREAM, "MIMIC-IV-Ext-Triage-Specialty-Diagnosis-Decision-Support.csv")
_SRC_DEV  = os.path.join(_UPSTREAM, "MIMIC-IV-Ext-Dev.csv")

# Canonical data/splits/ paths
TEST_CSV        = os.path.join(_SPLITS_DIR, "test.csv")
VAL_CSV         = os.path.join(_SPLITS_DIR, "val.csv")
SCRATCH_CSV     = os.path.join(_SPLITS_DIR, "scratch.csv")
DEV_CSV         = os.path.join(_SPLITS_DIR, "dev.csv")
DEV_TUNE_CSV    = os.path.join(_SPLITS_DIR, "dev_tune.csv")
DEV_HOLDOUT_CSV = os.path.join(_SPLITS_DIR, "dev_holdout.csv")

VAL_SIZE         = 2_000
SCRATCH_SIZE     = 100
DEV_TUNE_SIZE    = 1_000
DEV_HOLDOUT_SIZE = 500
SEED             = 42


def prepare(val_size: int = VAL_SIZE, scratch_size: int = SCRATCH_SIZE, seed: int = SEED) -> None:
    for src, label in [(_SRC_TEST, "test"), (_SRC_DEV, "dev (source)")]:
        if not os.path.exists(src):
            sys.exit(
                f"Source not found: {src}\n"
                "Run MIMIC-IV-Ext-Creation.py first to generate both benchmark CSVs."
            )

    # 1. Copy test into data/ (for naming consistency only -- do not use during dev)
    os.makedirs(_SPLITS_DIR, exist_ok=True)
    shutil.copy2(_SRC_TEST, TEST_CSV)
    print("Copied  -> data/splits/test.csv  (OFF-LIMITS)")

    # 2. Load full source pool, carve out val, save remainder as dev
    pool = pd.read_csv(_SRC_DEV)
    print(f"Source pool: {len(pool):,} rows")

    val       = pool.sample(n=val_size, random_state=seed)
    dev       = pool.drop(index=val.index)   # free development pool
    scratch   = dev.sample(n=scratch_size, random_state=seed)

    # Permutation-based split: tune and holdout are disjoint by construction
    rng = np.random.RandomState(seed)
    indices = rng.permutation(len(dev))
    dev_tune    = dev.iloc[indices[:DEV_TUNE_SIZE]].sort_values("stay_id").reset_index(drop=True)
    dev_holdout = dev.iloc[indices[DEV_TUNE_SIZE:DEV_TUNE_SIZE + DEV_HOLDOUT_SIZE]].sort_values("stay_id").reset_index(drop=True)

    val.to_csv(VAL_CSV, index=False)
    dev.to_csv(DEV_CSV, index=False)
    scratch.to_csv(SCRATCH_CSV, index=False)
    dev_tune.to_csv(DEV_TUNE_CSV, index=False)
    dev_holdout.to_csv(DEV_HOLDOUT_CSV, index=False)

    print(
        f"\nSplits written to data/splits/:\n"
        f"  test.csv        {2200:>6,}  OFF-LIMITS\n"
        f"  val.csv         {len(val):>6,}  locked  (seed={seed})\n"
        f"  scratch.csv     {len(scratch):>6,}  subset of dev  (seed={seed})\n"
        f"  dev.csv         {len(dev):>6,}  free development pool\n"
        f"  dev_tune.csv    {len(dev_tune):>6,}  experiment tuning  (seed={seed})\n"
        f"  dev_holdout.csv {len(dev_holdout):>6,}  final holdout  (seed={seed})"
    )

    # 3. Triage distribution check: pool vs val
    triage_col = next((c for c in pool.columns if c in ("triage", "acuity", "ESI")), None)
    if triage_col:
        pool_dist = pool[triage_col].value_counts(normalize=True).sort_index()
        val_dist  = val[triage_col].value_counts(normalize=True).sort_index()
        print("\nTriage distribution (source pool vs val):")
        for level in pool_dist.index.union(val_dist.index):
            p = pool_dist.get(level, 0.0)
            v = val_dist.get(level, 0.0)
            print(f"  ESI {level}: pool={p:.3f}  val={v:.3f}  |diff|={abs(p-v)*100:.1f}pp")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--val-size",     type=int, default=VAL_SIZE,     help=f"Val set size (default {VAL_SIZE})")
    parser.add_argument("--scratch-size", type=int, default=SCRATCH_SIZE, help=f"Scratch size (default {SCRATCH_SIZE})")
    parser.add_argument("--seed",         type=int, default=SEED,         help=f"Random seed (default {SEED})")
    args = parser.parse_args()

    prepare(val_size=args.val_size, scratch_size=args.scratch_size, seed=args.seed)
